name: policjawsylwestra
description: Prawo i niesprawiedliwość.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_map: ^0.10.1+1
  flutter_hooks: ^0.15.0
  cached_network_image: ^2.5.0
  latlong: ^0.6.1
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  location: ^3.2.1
  get_it: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  mobx_codegen:

flutter:
  uses-material-design: true

  assets:
    - assets/policeman.png

